version: '3.8'

services:
  mobart-worker:
    build: .
    container_name: mobart-worker
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    network_mode: host  # Use host network to access Go backend's Redis
    
# Note: We'll use the Redis from your Go backend instead of creating a separate one
# This ensures both services use the same Redis instance for pub/sub

volumes:
  redis_data:
    driver: local
